import 'dotenv/config';
import http from 'node:http';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { readFile } from 'node:fs/promises';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const frontendDirectory = path.join(__dirname, '..', 'frontend');
const port = Number(process.env.PORT) || 3000;
const mimeTypes = { '.html': 'text/html; charset=utf-8', '.css': 'text/css; charset=utf-8', '.js': 'text/javascript; charset=utf-8' };

function sendJson(response, status, body) { response.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store' }); response.end(JSON.stringify(body)); }
async function readBody(request) { let body = ''; for await (const chunk of request) body += chunk; return body ? JSON.parse(body) : {}; }
function buildPrompt(question, instruction = '') { return `You are a patient, accurate study assistant for a B.Tech student. Answer the question in simple language. Structure your response with these headings: Definition, Main Points, Example, Code Example (when applicable), Short Summary. ${instruction ? `Additional instruction: ${instruction}.` : ''} Question: ${question}`; }
async function callAi(messages) { if (!process.env.AI_API_KEY || !process.env.AI_API_URL) { const error = new Error('AI service is not configured'); error.code = 'NOT_CONFIGURED'; throw error; } const aiResponse = await fetch(process.env.AI_API_URL, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${process.env.AI_API_KEY}` }, body: JSON.stringify({ model: process.env.AI_MODEL || 'gpt-4o-mini', messages, temperature: 0.4 }) }); if (!aiResponse.ok) throw new Error('AI provider error'); const data = await aiResponse.json(); const answer = data.choices?.[0]?.message?.content; if (!answer) throw new Error('AI response was empty'); return answer; }
function quizPrompt(topic) { return `Create a quiz for a B.Tech student about ${topic}. Return ONLY valid JSON with this shape: {"questions":[{"question":"...","options":["...","...","...","..."],"correctIndex":0,"explanation":"..."}]}. Include exactly 5 multiple-choice questions. correctIndex must be a zero-based number.`; }
async function serveStatic(request, response) { const requestedPath = request.url === '/' ? 'index.html' : request.url.slice(1).split('?')[0]; const filePath = path.resolve(frontendDirectory, requestedPath); if (!filePath.startsWith(path.resolve(frontendDirectory))) return sendJson(response, 403, { error: 'Forbidden' }); try { const content = await readFile(filePath); response.writeHead(200, { 'Content-Type': mimeTypes[path.extname(filePath)] || 'application/octet-stream' }); response.end(content); } catch { const content = await readFile(path.join(frontendDirectory, 'index.html')); response.writeHead(200, { 'Content-Type': mimeTypes['.html'] }); response.end(content); } }
const server = http.createServer(async (request, response) => { try { if (request.method === 'POST' && request.url === '/api/ask') { const { question, instruction } = await readBody(request); if (!question?.trim()) return sendJson(response, 400, { error: 'Question is required' }); const answer = await callAi([{ role: 'system', content: 'You create clear, encouraging study explanations.' }, { role: 'user', content: buildPrompt(question.trim(), instruction) }]); return sendJson(response, 200, { answer }); } if (request.method === 'POST' && request.url === '/api/quiz') { const { topic } = await readBody(request); if (!topic?.trim()) return sendJson(response, 400, { error: 'Topic is required' }); const raw = await callAi([{ role: 'system', content: 'You return strictly valid JSON and no markdown.' }, { role: 'user', content: quizPrompt(topic.trim()) }]); return sendJson(response, 200, JSON.parse(raw)); } if (request.method === 'GET') return serveStatic(request, response); sendJson(response, 404, { error: 'Not found' }); } catch (error) { const status = error.code === 'NOT_CONFIGURED' ? 503 : 502; sendJson(response, status, { error: 'AI service is currently unavailable.' }); } });
server.listen(port, () => console.log(`AI Study Manager running at http://localhost:${port}`));
